version: 1.0.{build}

image: Ubuntu1804

init:
- sh: >-
    sudo apt-get update

    sudo apt-get install --quiet --yes sdcc libusb-1.0-0-dev doxygen doxygen-doc doxygen-gui graphviz rubber

build_script:
- sh: make dist

artifacts:
- path: build/fx2-devel.tgz
  name: fx2-devel.tgz
